
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Notification email'
      Parameters:
      - EndpointId
    - Label:
        default: 'NAT Gateway'
      Parameters:
      - NatGatewayId
    - Label:
        default: 'Thresholds'
      Parameters:
      - ErrorPortAllocationThreshold
      - PacketsDropCountThreshold
      - BandwidthUtilizationThreshold
      - PacketsUtilizationThreshold
Parameters:
  EndpointId:
    Description: 'Your email address to receive alert message'
    Type: String
  NatGatewayId:
    Description: 'The NAT gateway ID that you want to monitor.'
    Type: String
  ErrorPortAllocationThreshold:
    Description: 'The maximum port allocation errors (set to -1 to disable).'
    Type: Number
    Default: 0
    MinValue: -1
  PacketsDropCountThreshold:
    Description: 'The maximum packet drops (set to -1 to disable).'
    Type: Number
    Default: 0
    MinValue: -1
  BandwidthUtilizationThreshold:
    Description: 'The maximum percentage of bandwidth utilization (set to -1 to disable).'
    Type: Number
    Default: 80
    MinValue: -1
    MaxValue: 100
  PacketsUtilizationThreshold:
    Description: 'The maximum percentage of packets utilization (set to -1 to disable).'
    Type: Number
    Default: 80
    MinValue: -1
    MaxValue: 100
Conditions:
  HasErrorPortAllocationThreshold: !Not [!Equals [!Ref ErrorPortAllocationThreshold, '-1']]
  HasPacketsDropCountThreshold: !Not [!Equals [!Ref PacketsDropCountThreshold, '-1']]
  HasBandwidthUtilizationThreshold: !Not [!Equals [!Ref BandwidthUtilizationThreshold, '-1']]
  HasPacketsUtilizationThreshold: !Not [!Equals [!Ref PacketsUtilizationThreshold, '-1']]
Resources:
  ##########################################################################
  #                                                                        #
  #                                 TOPIC                                  #
  #                                                                        #
  ##########################################################################
  Topic:
    Type: 'AWS::SNS::Topic'
    Properties: {}
  TopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Id: Id1
        Version: '2012-10-17'
        Statement:
        - Sid: Sid1
          Effect: Allow
          Principal:
            Service: 'events.amazonaws.com' # Allow EventBridge
          Action: 'sns:Publish'
          Resource: !Ref Topic
        - Sid: Sid2
          Effect: Allow
          Principal:
            AWS: '*' # Allow CloudWatch Alarms
          Action: 'sns:Publish'
          Resource: !Ref Topic
          Condition:
            StringEquals:
              'AWS:SourceOwner': !Ref 'AWS::AccountId'
      Topics:
      - !Ref Topic
  TopicEndpointSubscription:
    DependsOn: TopicPolicy
    Type: 'AWS::SNS::Subscription'
    Properties:
      DeliveryPolicy:
        healthyRetryPolicy:
          minDelayTarget: 1
          maxDelayTarget: 60
          numRetries: 100
          numNoDelayRetries: 0
          backoffFunction: exponential
        throttlePolicy:
          maxReceivesPerSecond: 1
      Endpoint: !Ref EndpointId
      Protocol: email
      TopicArn: !Ref Topic
  MonitoringNGWEvent:
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Monitoring NAT Gateway Utilization'
      ScheduleExpression: 'rate(30 days)'
      State: ENABLED
      Targets:
      - Arn: !Ref Topic
        Id: ngw
        Input: !Sub |
          {
            "Type": "monitoring nat gateway",
            "StackTemplate": "monitor-nat-gateway",
            "StackVersion": "1.0",
            "Partition": "${AWS::Partition}",
            "AccountId": "${AWS::AccountId}",
            "Region": "${AWS::Region}",
            "StackId": "${AWS::StackId}",
            "StackName": "${AWS::StackName}"
          }
  ##########################################################################
  #                                                                        #
  #                                 ALARMS                                 #
  #                                                                        #
  ##########################################################################
  ErrorPortAllocationTooHighAlarm:
    Condition: HasErrorPortAllocationThreshold
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmDescription: 'Errors allocating a source port over last 10 minutes too high. Too many concurrent connections are open through the NAT gateway. (created by marbot)'
      Namespace: 'AWS/NATGateway'
      MetricName: ErrorPortAllocation
      Statistic: Sum
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: !Ref ErrorPortAllocationThreshold
      Dimensions:
      - Name: NatGatewayId
        Value: !Ref NatGatewayId
  PacketsDropCountTooHighAlarm:
    Condition: HasPacketsDropCountThreshold
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmDescription: 'Dropped packets over last 10 minutes too high. This might indicate an ongoing transient issue with the NAT gateway. (created by marbot)'
      Namespace: 'AWS/NATGateway'
      MetricName: PacketsDropCount
      Statistic: Sum
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: !Ref PacketsDropCountThreshold
      Dimensions:
      - Name: NatGatewayId
        Value: !Ref NatGatewayId
  BandwidthUtilizationTooHighAlarm:
    Condition: HasBandwidthUtilizationThreshold
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmDescription: 'Bandwidth utilization too high. (created by marbot)'
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Metrics:
      - Id: 'in1'
        Label: 'InFromDestination'
        MetricStat:
          Metric:
            Namespace: 'AWS/NATGateway'
            MetricName: BytesInFromDestination # bytes per minute
            Dimensions:
            - Name: NatGatewayId
              Value: !Ref NatGatewayId
          Period: 60
          Stat: Sum
          Unit: Bytes
        ReturnData: false
      - Id: 'in2'
        Label: 'InFromSource'
        MetricStat:
          Metric:
            Namespace: 'AWS/NATGateway'
            MetricName: BytesInFromSource # bytes per minute
            Dimensions:
            - Name: NatGatewayId
              Value: !Ref NatGatewayId
          Period: 60
          Stat: Sum
          Unit: Bytes
        ReturnData: false
      - Id: 'out1'
        Label: 'OutToDestination'
        MetricStat:
          Metric:
            Namespace: 'AWS/NATGateway'
            MetricName: BytesOutToDestination # bytes per minute
            Dimensions:
            - Name: NatGatewayId
              Value: !Ref NatGatewayId
          Period: 60
          Stat: Sum
          Unit: Bytes
        ReturnData: false
      - Id: 'out2'
        Label: 'OutToSource'
        MetricStat:
          Metric:
            Namespace: 'AWS/NATGateway'
            MetricName: BytesOutToSource # bytes per minute
            Dimensions:
            - Name: NatGatewayId
              Value: !Ref NatGatewayId
          Period: 60
          Stat: Sum
          Unit: Bytes
        ReturnData: false
      - Expression: '(in1+in2+out1+out2)/60*8/1000/1000/1000' # to Gbit/s
        Id: 'bandwidth'
        Label: 'Bandwidth'
        ReturnData: false
      - Expression: 'bandwidth/100*100' # hard limit is 100 Gbit/s
        Id: 'utilization'
        Label: 'Utilization'
        ReturnData: true
      Threshold: !Ref BandwidthUtilizationThreshold
      TreatMissingData: notBreaching
  PacketsUtilizationTooHighAlarm:
    Condition: HasPacketsUtilizationThreshold
    DependsOn: TopicEndpointSubscription
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmActions:
      - !Ref Topic
      AlarmDescription: 'Packets utilization too high. (created by marbot)'
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Metrics:
      - Id: 'in1'
        Label: 'InFromDestination'
        MetricStat:
          Metric:
            Namespace: 'AWS/NATGateway'
            MetricName: BytesInFromDestination # packets per minute
            Dimensions:
            - Name: NatGatewayId
              Value: !Ref NatGatewayId
          Period: 60
          Stat: Sum
          Unit: Count
        ReturnData: false
      - Id: 'in2'
        Label: 'InFromSource'
        MetricStat:
          Metric:
            Namespace: 'AWS/NATGateway'
            MetricName: BytesInFromSource # packets per minute
            Dimensions:
            - Name: NatGatewayId
              Value: !Ref NatGatewayId
          Period: 60
          Stat: Sum
          Unit: Count
        ReturnData: false
      - Id: 'out1'
        Label: 'OutToDestination'
        MetricStat:
          Metric:
            Namespace: 'AWS/NATGateway'
            MetricName: PacketsOutToDestination # packets per minute
            Dimensions:
            - Name: NatGatewayId
              Value: !Ref NatGatewayId
          Period: 60
          Stat: Sum
          Unit: Count
        ReturnData: false
      - Id: 'out2'
        Label: 'OutToSource'
        MetricStat:
          Metric:
            Namespace: 'AWS/NATGateway'
            MetricName: PacketsOutToSource # packets per minute
            Dimensions:
            - Name: NatGatewayId
              Value: !Ref NatGatewayId
          Period: 60
          Stat: Sum
          Unit: Count
        ReturnData: false
      - Expression: '(in1+in2+out1+out2)/60' # to packets per second
        Id: 'packets'
        Label: 'Packets'
        ReturnData: false
      - Expression: 'packets/10000000*100' # hard limit is 10,000,000 packets per second
        Id: 'utilization'
        Label: 'Utilization'
        ReturnData: true
      Threshold: !Ref PacketsUtilizationThreshold
      TreatMissingData: notBreaching
  NatGatewayDashboard:
      Type: 'AWS::CloudWatch::Dashboard'
      Properties:
        DashboardName: 'NATGatewayDashboard'
        DashboardBody: !Sub |
          {
            "widgets": [
              {
                "type": "metric",
                "x": 0,
                "y": 0,
                "width": 12,
                "height": 6,
                "properties": {
                  "region": "${AWS::Region}",
                  "metrics": [
                    [ "AWS/NATGateway", "BytesInFromDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m1", "visible": false} ],
                    [ ".", "BytesInFromSource", "NatGatewayId", "${NatGatewayId}",{"id": "m2", "visible": false} ],
                    [ ".", "BytesOutToDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m3", "visible": false} ],
                    [ ".", "BytesOutToSource", "NatGatewayId", "${NatGatewayId}",{"id": "m4", "visible": false} ],
                    [ { "expression": "(m1 + m2 + m3 + m4)/60", "label": "Bytes", "id": "e1" } ]
                  ],

                  "view": "timeSeries",
                  "stacked": false,
                  "title": "Bandwidth",
                  "yAxis": {  
                    "left": {
                      "min": 0
                    }
                  },
                  "stat": "Sum",
                  "period": 60
                }
              },
              {
                "type": "metric",
                "x": 0,
                "y": 6,
                "width": 12,
                "height": 6,
                "properties": {
                  "region": "${AWS::Region}",
                  "metrics": [
                    [ "AWS/NATGateway", "PacketsInFromDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m1", "visible": false} ],
                    [ ".", "PacketsInFromSource", "NatGatewayId", "${NatGatewayId}",{"id": "m2", "visible": false} ],
                    [ ".", "PacketsOutToDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m3", "visible": false} ],
                    [ ".", "PacketsOutToSource", "NatGatewayId", "${NatGatewayId}",{"id": "m4", "visible": false} ],
                    [ { "expression": "(m1 + m2 + m3 + m4)/60", "label": "Packets", "id": "e1" } ]
                  ],
                  "view": "timeSeries",
                  "stacked": false,
                  "title": "Packets",
                  "yAxis": {
                    "left": {
                      "min": 0
                    }
                  },
                  "stat": "Sum",
                  "period": 60
                }
              },
              {
                "type": "metric",
                "x": 12,
                "y": 0,
                "width": 12,
                "height": 6,
                "properties": {
                  "region": "${AWS::Region}",
                  "metrics": [
                    [ "AWS/NATGateway", "BytesInFromDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m1", "visible": false} ],
                    [ ".", "BytesInFromSource", "NatGatewayId", "${NatGatewayId}",{"id": "m2", "visible": false} ],
                    [ ".", "BytesOutToDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m3", "visible": false} ],
                    [ ".", "BytesOutToSource", "NatGatewayId", "${NatGatewayId}",{"id": "m4", "visible": false} ],
                    [ { "expression": "(m1 + m2 + m3 + m4)/60*8/1000/1000/1000/100*100", "label": "Utilization", "id": "e1" } ]
                  ],
                  "view": "timeSeries",
                  "stacked": false,
                  "title": "Bandwidth Utilization",
                  "yAxis": {
                    "left": {
                      "min": 0
                    }
                  },
                  "stat": "Sum",
                  "period": 60
                }
              },
              {
                "type": "metric",
                "x": 12,
                "y": 0,
                "width": 12,
                "height": 6,
                "properties": {
                  "region": "${AWS::Region}",
                  "metrics": [
                    [ "AWS/NATGateway", "PacketsInFromDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m1", "visible": false} ],
                    [ ".", "PacketsInFromSource", "NatGatewayId", "${NatGatewayId}",{"id": "m2", "visible": false} ],
                    [ ".", "PacketsOutToDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m3", "visible": false} ],
                    [ ".", "PacketsOutToSource", "NatGatewayId", "${NatGatewayId}",{"id": "m4", "visible": false} ],
                    [ { "expression": "(m1 + m2 + m3 + m4)/60/10000000*100", "label": "Utilization", "id": "e1" } ]
                  ],
                  "view": "timeSeries",
                  "stacked": false,
                  "title": "Packets Utilization",
                  "yAxis": {
                    "left": {
                      "min": 0
                    }
                  },
                  "stat": "Sum",
                  "period": 60
                }
              },
              {
                "type": "metric",
                "x": 6,
                "y": 6,
                "width": 6,
                "height": 6,
                "properties": {
                  "region": "${AWS::Region}",
                  "metrics": [
                    [ "AWS/NATGateway", "BytesInFromDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m1", "visible": false} ],
                    [ ".", "BytesInFromSource", "NatGatewayId", "${NatGatewayId}",{"id": "m2", "visible": false} ],
                    [ ".", "BytesOutToDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m3", "visible": false} ],
                    [ ".", "BytesOutToSource", "NatGatewayId", "${NatGatewayId}",{"id": "m4", "visible": false} ],
                    [ { "expression": "(m1 + m2 + m3 + m4)/60*8/1000/1000/1000/100*100", "label": "Utilization", "id": "e1" } ]
                  ],
                  "view": "gauge",
                  "title": "Bandwidth Utilization Gauge",
                  "yAxis": {
                    "left": {
                      "min": 0,
                      "max": 100
                    }
                  }
                }   
              },
              {
                "type": "metric",
                "x": 0,
                "y": 6,
                "width": 6,
                "height": 6,
                "properties": {
                  "region": "${AWS::Region}",
                  "metrics": [
                    [ "AWS/NATGateway", "PacketsInFromDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m1", "visible": false} ],
                    [ ".", "PacketsInFromSource", "NatGatewayId", "${NatGatewayId}",{"id": "m2", "visible": false} ],
                    [ ".", "PacketsOutToDestination", "NatGatewayId", "${NatGatewayId}",{"id": "m3", "visible": false} ],
                    [ ".", "PacketsOutToSource", "NatGatewayId", "${NatGatewayId}",{"id": "m4", "visible": false} ],
                    [ { "expression": "(m1 + m2 + m3 + m4)/60/10000000*100", "label": "Utilization", "id": "e1" } ]
                  ],
                  "view": "gauge",
                  "title": "Packages Utilization Gauge",
                  "yAxis": {
                    "left": {
                      "min": 0,
                      "max": 100
                    }
                  }
                }   
              }
            ]
          }

Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  StackTemplate:
    Description: 'Stack template.'
    Value: 'monitor-nat-gateway'
  StackVersion:
    Description: 'Stack version.'
    Value: '1.0'


  
